name: Release

on:
  schedule:
    - cron: '0 0 * * 0'  # Trigger every Sunday at midnight
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.event.repository.pushed_at != github.event.repository.updated_at }}  # Only trigger if there are new commits in the main branch

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Install Gorelaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          futureRelease: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
